exclude all-nan samples from distance heatmap
onecodex/onecodex pull request #455
Opened 2023-07-28 23:55 UTC by alenajk

## Status
- [x] **Ready**

## Description
We want to totally exclude samples that have no abundances calculated for them from the distance heatmap plot. This adds `exclude_all_nan` to a few places with a default of `False`, and a call to `_cluster_by_sample` with `exclude_all_nan=True` to get the desired results.

## Related PRs
- [ x] This PR is independent

## TODOs
Add any todos here as needed for work in progress code. This section can be deleted if not relevant. Examples:

- [ ] Tests
- [ ] Documentation

2023-08-01 19:28 UTC, jairideout requested changes

2023-08-16 18:29 UTC, jairideout requested changes

2023-08-16 18:29 UTC, jairideout commented on onecodex/viz/_distance.py
> +            warnings.warn(
This doesn't raise a warning for me. The first arg to `warnings.warn` should be the message and the second arg is the warning type:

```python
warnings.warn(
    f"{len(self._all_nan_classification_ids)} sample(s) have no abundances calculated and have been omitted from the distance heatmap.",
    PlottingWarning,
)
```

2023-08-16 22:10 UTC, jairideout approved these changes

2023-08-18 17:23 UTC, audy approved these changes

2023-08-18 17:58 UTC, merged